apiVersion: v2
name: metrics-governor
description: OTLP metrics proxy with buffering, statistics tracking, and adaptive limits enforcement
type: application
version: 0.9.6
appVersion: "0.20.0"
keywords:
  - otlp
  - metrics
  - proxy
  - opentelemetry
  - cardinality
  - limits
home: https://github.com/szibis/metrics-governor
sources:
  - https://github.com/szibis/metrics-governor
maintainers:
  - name: szibis
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: monitoring-logging
