apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metrics-governor.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metrics-governor.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "metrics-governor.configYAML" . | nindent 4 }}
