{{- if and .Values.sampling.enabled (not .Values.sampling.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metrics-governor.samplingConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metrics-governor.labels" . | nindent 4 }}
data:
  sampling.yaml: |
    {{- .Values.sampling.config | nindent 4 }}
{{- end }}
