{{- if and .Values.limits.enabled (not .Values.limits.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metrics-governor.limitsConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metrics-governor.labels" . | nindent 4 }}
data:
  limits.yaml: |
    {{- .Values.limits.config | nindent 4 }}
{{- end }}
